config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions", :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_scope :user do
    get '/users/detail',  to: 'registrations#detail'
    put '/users/detail',  to: 'registrations#detail_update'
  end

  root 'home#index'
  get   '/terms',          to:  'home#terms'
  get   '/facebook_registration',          to:  'home#registration'
  put   '/facebook_registration',          to:  'home#registration_update'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :users

  get '/users/:id/payment', to: 'users#payment', as: :users_payment
  put '/users/:id/payment', to: 'users#transaction', as: :users_transaction
  get '/users/:id/wait', to: 'users#wait', as: :users_wait

  get '/dashboard',       to: 'dashboard#index'
  post '/rating',          to: 'users#rating'

  get '/settings',            to: 'settings#index'
  put '/settings',            to: 'settings#update'
  get '/settings/password',   to: 'settings#password', as: :settings_password
  put '/settings/password',   to: 'settings#change_password'
  get '/settings/payment',    to: 'settings#payment', as: :settings_payment
  put '/settings/payment',    to: 'payment#set_default'
  get '/settings/payment/new',to: 'settings#add_payment', as: :settings_add_payment
  get '/settings/category',   to: 'settings#category'
  get '/settings/mentor',   to: 'settings#mentor'
  put '/settings/mentor',   to: 'settings#mentor_create'
  put '/settings/mentor/detail',   to: 'settings#mentor_detail'
  put '/settings/mentor/update',   to: 'settings#mentor_update'
  put '/settings/mentor/status',   to: 'settings#mentor_status'


  get  '/payment',        to: 'payment#new', as: :new_payment
  post '/payment/:id/set_default', to: 'payment#set_default', as: :set_default_payment
  post '/payment',        to: 'payment#create'
  delete '/payment/:id',  to: 'payment#destroy', as: :destroy_payment


  put '/category/create_relation', to: 'category#create_category_user_relation'
  put '/category/delete_relation', to: 'category#delete_category_user_relation'
  put '/category/update_current', to: 'category#update_current'
  put '/category/update_desire', to: 'category#update_desire'
  put '/category/update_desire', to: 'category#update_desire'
  put '/category/relation', to: 'category#relation'
  put '/category/relation_one', to: 'category#relation_one'

  put '/feed_message',    to: 'feed_message#create'
  put '/feed_message/update',    to: 'feed_message#update'
  put '/feed_message/upload',    to: 'feed_message#upload'
  put '/feed_message/share',    to: 'feed_message#share'

  put '/follow',    to: 'follow#create'
  put '/follow/delete',    to: 'follow#delete'

  get '/notifications', to: 'notifications#index'
  post '/notifications/resources', to: 'notifications#resources'
  put '/notifications/delete', to: 'notifications#delete'

  put '/payment/accept', to: 'payment#accept'
  put '/payment/decline', to: 'payment#decline'

  resources :message

  put '/message/update', to: 'message#update'
  put '/reply/upload', to: 'conversation_reply#upload'
  post '/reply/delete', to: 'conversation_reply#delete'
  
  get  '/search',        to: 'search#new', as: :search

  get  '/resources',        to: 'resources#new', as: :resources
  put  '/resources/upload',        to: 'resources#upload'
  get  '/resources/admin',        to: 'resources#admin'
  put  '/resources/admin',        to: 'resources#upload_default'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                       :integer          not null, primary key
#  email                    :string           default(""), not null
#  encrypted_password       :string           default(""), not null
#  reset_password_token     :string
#  reset_password_sent_at   :datetime
#  remember_created_at      :datetime
#  sign_in_count            :integer          default(0), not null
#  current_sign_in_at       :datetime
#  last_sign_in_at          :datetime
#  current_sign_in_ip       :inet
#  last_sign_in_ip          :inet
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  username                 :string
#  first_name               :string
#  middle_name              :string
#  last_name                :string
#  address                  :string
#  city                     :string
#  state                    :string
#  zipcode                  :string
#  birthdate                :date
#  country                  :string(2)
#  prefered_language        :string(2)
#  user_type                :integer
#  mobile_phone             :string
#  terms_of_service         :boolean
#  default_payment_id       :integer
#  gender                   :string
#  security_question_id     :integer
#  security_question_answer :string
#  avatar_file_name         :string
#  avatar_content_type      :string
#  avatar_file_size         :integer
#  avatar_updated_at        :datetime
#  education                :string
#  about                    :string
#  program                  :string
#  terms                    :string
#  provider                 :string
#  uid                      :string
#  mentor_status            :boolean          default(TRUE)
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  enum user_type: { mentee: 0, mentor: 1, both: 2 }
  enum gender: { male: 'male', female: 'female' }
  
  TEMP_EMAIL_PREFIX = 'change@me'
  TEMP_EMAIL_REGEX = /\Achange@me/

  has_many :categorys, through: :categorys_users_relations 
  has_many :categorys_users_relations
  has_many :feed_messages, class_name: 'FeedMessage', foreign_key: :reciever_id
  has_many :follows
  has_many :ratings
  has_many :courses
  has_many :payments
  has_many :transactions
  has_many :notifications
  has_many :courses_user_relations

  belongs_to :default_payment, class_name: 'Payment'

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  extend FriendlyId
  friendly_id :username

  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "images/:style/avatar.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  validates :email, uniqueness: true
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :username, length: { maximum: 32 }
  
  def self.find_for_oauth(auth, signed_in_resource = nil)

    # Get the identity and user if they exist
    identity = Identity.find_for_oauth(auth)

    # If a signed_in_resource is provided it always overrides the existing user
    # to prevent the identity being locked with accidentally created accounts.
    # Note that this may leave zombie accounts (with no associated identity) which
    # can be cleaned up at a later date.
    user = signed_in_resource ? signed_in_resource : identity.user

    # Create the user if needed
    if user.nil?

      # Get the existing user by email if the provider gives us a verified email.
      # If no verified email was provided we assign a temporary email and ask the
      # user to verify it on the next step via UsersController.finish_signup
      email_is_verified = auth.info.email && (auth.info.verified || auth.info.verified_email)
      email = auth.info.email
      user = User.where(:email => email).first if email

      user_info = auth.extra.raw_info.name.split(' ')


      # Create the user if it's a new registration
      if user.nil?
        user = User.new(
          username: auth.uid,
          first_name: user_info[0],
          last_name: user_info[1],
          terms_of_service: false,
          email: email,
          password: Devise.friendly_token[0,20]
        )
        user.save!
      end
    end

    # Associate the identity with the user if needed
    if identity.user != user
      identity.user = user
      identity.save!
    end
    user
  end

  def self.search(search)
    time = 6.month.ago
    User.joins("LEFT JOIN courses ON courses.user_id = users.id
            LEFT JOIN categories ON courses.categories_id = categories.id 
            LEFT JOIN ratings ON users.id = ratings.user_id AND ratings.updated_at >= '#{time}'")
    .where("lower(first_name) LIKE ? OR lower(last_name) LIKE ? OR lower(categories.name) LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
    .group("users.id")
    .order("avg(ratings.value) ASC")
  end

  def email_verified?
    self.email && self.email !~ TEMP_EMAIL_REGEX
  end

  def booked_number
    CoursesUserRelation.where(owner: self).where('created_at >= ?', 2.week.ago).count
  end

  def compatibility(user)
    a = []
    CategorysUsersRelation.where(user: user).each { |r| a << r.category_id } 
    
    a2 = []
    Course.where(user: self).each { |d| a2 << d.categories_id }

    com_count = 0

    a.each do |v| 
      com_count += 1 if a2.include?(v)
    end
    
    unless a.length == 0
      (com_count.to_f / a.length ) * 100
    else
      0
    end
  end

  def hold_transaction(course_id, payment_id)
    course = Course.find(course_id)
    payment = Payment.find(payment_id)
    BraintreeApi.new.hold_amount(course, payment)
  end

  def collect_transaction(transaction, noticification)
    BraintreeApi.new.collect_amount(transaction, noticification)
  end

  def release_transaction(transaction, noticification)
    BraintreeApi.new.release_amount(transaction, noticification)
  end

  def mentor_area_exist?(category)
    categories = Category.where(parent_id: category)
    Course.where(user: self, categories: categories).present?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :incomplete_info_user!, except: :show
  before_action :set_user, only: [:show, :edit, :update, :destroy, :payment, :transaction, :wait]

  def index
    if user_signed_in?
      redirect_to dashboard_path
    else
      redirect_to new_user_registration_path
    end
  end
  # GET /users/:id.:format
  def show
    @category = Category.where(parent_id: nil)
    user_ids = feed_message_user
    @feed_message = FeedMessage.where(sender_id: user_ids).order("created_at DESC")
    @feed = FeedMessage.new
  end

  # GET /users/:id/edit
  def edit
    # authorize! :update, @user
  end

  # PATCH/PUT /users/:id.:format
  def update
    # authorize! :update, @user
    respond_to do |format|
      if @user.update(user_params)
        sign_in(@user == current_user ? @user : current_user, :bypass => true)
        format.html { redirect_to @user, notice: 'Your profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET/PATCH /users/:id/finish_signup
  def finish_signup
    # authorize! :update, @user 
    if request.patch? && params[:user] #&& params[:user][:email]
      if @user.update(user_params)
        sign_in(@user, :bypass => true)
        redirect_to users_detail_path(@user), notice: 'Your profile was successfully updated.'
      else
        @show_errors = true
      end
    else
      redirect_to users_path(@user)
    end
  end

  # DELETE /users/:id.:format
  def destroy
    # authorize! :delete, @user
    @user.destroy
    respond_to do |format|
      format.html { redirect_to root_url }
      format.json { head :no_content }
    end
  end

  def payment
    if params.has_key?(:id) and params.has_key?(:course)
      @payments = current_user.payments
      @course = Course.find(params[:course])
    else
      redirect_to user_path(current_user)
    end
  end

  def transaction
    if params[:payment].present?
      current_user.hold_transaction(params[:course], params[:payment])
      redirect_to users_wait_path
    else
      respond_to do |format|
        format.html { redirect_to request.referer, notice: 'Your transaction has problem!!!.' }
        format.json { head :no_content }
      end
    end
  end

  def wait
  end

  def rating
    rating = Rating.where(user_id: params[:user], giver: current_user, courses_user_relation_id: params[:courses_user_relations]).first_or_create!
    rating.value = params[:value]
    rating.save!
    render json: { success: true, value: rating.value, status: 200 }
  end

private
  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    accessible = [ :name, :email ] # extend with your own params
    accessible << [ :password, :password_confirmation ] unless params[:user][:password].blank?
    params.require(:user).permit(accessible)
  end

  def feed_message_user
    user_array = Array.new
    for f in @user.follows
      user_array << f.follower.id
    end

    user_array << @user.id
  end
end

app/views/users/_category.html.haml
- for category in @category
  - if category.category_user_exist?(@user, category.id)
    - cat = CategorysUsersRelation.joins(:category).where(categories: {parent_id: category.id}, user: @user)
    %h6.center.sliders
      #{category.name}
    .range-field  
      .progress.action{ ref: "#{category.id}" }
        .determinate.determinate_base{ ref: "#{category.id}", style: "width: #{cat.average(:value).to_i}%" }

app/views/users/_feed_message.html.haml
- if !@feed_message.present?
  %h5.js-no-content.center
    = "-- No content --"
  %ol.chat
- else
  %ol.chat
    - for msg in @feed_message
      - if msg.sender == @user
        %li.self.animated.slideInDown
          .avatar
            = image_tag msg.sender.avatar.url(:thumb)
          .msg
            %h5.msg-name.center #{msg.sender.first_name}
            - if msg.message.present?
              %p #{msg.message}
            - elsif msg.image.present?
              %p 
                = image_tag msg.image.url(:thumb)
            - elsif msg.ref_feed_message.present?
              - if msg.ref_feed_message.message.present?
                %p 
                  #{msg.ref_feed_message.message}
                .credit-msg
                  %i.fa.fa-retweet{"aria-hidden" => "true"}
                  Shared from
                  = link_to msg.ref_feed_message.sender.first_name, user_path(msg.ref_feed_message.sender)
              - elsif msg.ref_feed_message.image.present?
                %p 
                  = image_tag msg.ref_feed_message.image.url(:thumb)
                .credit-msg
                  %i.fa.fa-retweet{"aria-hidden" => "true"}
                  Shared from
                  = link_to msg.ref_feed_message.sender.first_name, user_path(msg.ref_feed_message.sender)
            %time 
              - if msg.created_at.today?
                = msg.created_at.strftime("%I:%M %p") 
              - else
                = msg.created_at.strftime("%a/%m - %I:%M %p")
        - if msg.sender != current_user and current_user.present? and !msg.ref_feed_message.present?
          %a.waves-effect.waves-teal.btn-flat.right.js-share-feed{style: "margin-right: 6%;", ref: msg.id}
            Share
            %i.fa.fa-heart{"aria-hidden" => "true"}
      - else
        %li.other.animated.slideInDown
          .avatar
            = image_tag msg.sender.avatar.url(:thumb)
          .msg
            %h5.msg-name.center #{msg.sender.first_name}
            - if msg.message.present?
              %p #{msg.message}
            - elsif msg.image.present?
              %p 
                = image_tag msg.image.url(:thumb)
            - elsif msg.ref_feed_message.present?
              - if msg.ref_feed_message.message.present?
                %p 
                  #{msg.ref_feed_message.message}
                .credit-msg
                  %i.fa.fa-retweet{"aria-hidden" => "true"}
                  Shared from
                  = link_to msg.ref_feed_message.sender.first_name, user_path(msg.ref_feed_message.sender)
              - elsif msg.ref_feed_message.image.present?
                %p 
                  = image_tag msg.ref_feed_message.image.url(:thumb)
                .credit-msg
                  %i.fa.fa-retweet{"aria-hidden" => "true"}
                  Shared from
                  = link_to msg.ref_feed_message.sender.first_name, user_path(msg.ref_feed_message.sender)
            %time
              - if msg.created_at.today?
                = msg.created_at.strftime("%I:%M %p") 
              - else
                = msg.created_at.strftime("%a/%m - %I:%M %p")
        - if msg.sender != current_user and current_user.present? and !msg.ref_feed_message.present?
          %a.waves-effect.waves-teal.btn-flat.js-share-feed{ style: "margin-left: 4%;", ref: msg.id }
            Share
            %i.fa.fa-heart{"aria-hidden" => "true"}

app/views/users/_feed_message_container.html.haml
#js-feed-container.feed-container.animated.fadeInRight
  - if @user == current_user
    .row
      .row
        .input-field.col.s12
          %textarea#feed-message-area.materialize-textarea.feed-message-area{:placeholder => "Share your ideas, concepts, motivations... anything..."}
          %label{:for => "feed-message-area"}
        %div{:style => "text-align: right;"}
          %a.btn-floating.btn-large.waves-effect.waves-light.btn-flat
            = form_for(@feed, url: feed_message_upload_path, html: { method: :put , class: 'feed-attach-form' }) do |f|
              = f.file_field :image, class: 'hide feed_message_upload'
              %i.material-icons.black-text.feed-attach attach_file
          %button.btn.waves-effect.waves-light.feed-message-button{:name => "action", :type => "submit", id: "js-feed-message-button"}
            Share

  .hide
    = image_tag "images/thumb/avatar.png", class: 'hide', id: 'default-img'
    = hidden_field_tag 'js-feed-reciever', @user.id
    = hidden_field_tag 'js-feed-sender', @user.id
    = hidden_field_tag 'js-newest-message', @feed_message.first.id if @feed_message.present?
    - if current_user.present?
      = hidden_field_tag 'js-feed-current-user', current_user.id
    
  .feeds
    = render 'feed_message'

app/views/users/_mentee.html.haml
.mentees
  %span.mentor-label My mentees:
  %br/
  .mentee-list
    %ul.lists
      - for f in @user.follows.mentees
        = link_to user_path(f.follower), style: 'margin-bottom: 5px;' do
          %li
            = image_tag f.follower.avatar.url(:thumb), :class => "circle list-pics mentee"
            %span.mentor-name #{f.follower.first_name}

app/views/users/_mentor.html.haml
.mentors
  %span.mentor-label My mentors:
  %br/
  .mentor-list
    %ul.lists
      - for f in @user.follows.mentors
        = link_to user_path(f.follower), style: 'margin-bottom: 5px;' do
          %li
            = image_tag f.follower.avatar.url(:thumb), :class => "circle list-pics"
            %span.mentor-name #{f.follower.first_name}
- if @course_user_relation.present?
  .refund-container
    %a.waves-effect.waves-light.btn.modal-trigger.white-text{:href => "#refund-modal"} Request a refund

app/views/users/_modal.html.haml
#modal-track.modal
  .modal-content
    .row
      .col.s4.progress-bar-content
      .col.s8.progress-content
        %span{ id: 'close'}x
        .row
          .col.s12.center
            %h4.progress-body-header
        .row.progress-range-content
          %input{ type: 'hidden', id: 'parent_category'}
          %input{ type: 'hidden', id: 'current_category'}
          .col.s6.center
            %label 
              Current Level
              %span{ class: "range_badge current_badge" } 
                0
          .col.s6.center
            %label 
              Desired Level
              %span{ class: "range_badge desired_badge" } 
                0
        .row.progress-range-content
          .col.s6
            .progress-range
              = range_field_tag("current_level", 0, { class: 'current_level_range', style: 'border: none;', min: 0, max: 100 })
          .col.s6
            .progress-range
              = range_field_tag("desired_level", 0, { class: 'desired_level_range', style: 'border: none;', min: 0, max: 100 })
              

app/views/users/_modalContact.html.haml
#contact-modal{class: 'modal bottom-sheet modal-fixed-footer'} 
  .modat-content
    %h4 Send contact request
    = form_for(@user, url: users_payment_path(@user), html: { method: :get }) do |f|
      .categories
        %li.category-list
          %h5 Select the category you want to send invitation for
        - for course in @user.courses
          %li.category-list
            = radio_button_tag :course, course.id, {class: 'with-gap'}
            = label :course, course.categories.name + " ($ #{course.price} per fortnight)", :for=> 'course_' + course.id.to_s


      .modal-footer
        = f.submit "Send", { class: 'modal-action modal-close waves-effect waves-green btn-flat' }
        %a{ href: "#!", class: 'modal-action modal-close close waves-effect waves-green btn-flat'} Cancel
- if current_user.present?
  #refund-modal.modal
    .modal-content
      %h4 Not satisfied with the mentor? Request a refund!
      .input-field.col.s12
        %select.course-refund
          %option{:disabled => "disabled", :selected => "selected", :value => ""} Choose your course
          - for course in @course_user_relation
            %option{:value => "#{course.id}"} #{course.course.categories.name}
      .input-field.col.s12
        %textarea#reason-refund.materialize-textarea{:length => "150"}
        %label{:for => "reason-refund"} Reason for refund?
    .modal-footer
      %a.modal-action.modal-close.waves-effect.waves-green.btn-flat{:onclick => "Materialize.toast('An email is sent for the refund. Our team will get back to you. Thanks!', 4000, 'rounded')"} Request

app/views/users/index.html.haml
%h3
  user

app/views/users/payment.html.haml
.row.setting-page
  .col.s12
    .row
      .form-fill
        = form_for(current_user, url: users_transaction_path(@user), html: { method: :put }) do |f|
          .course-container
            %h3{ class: 'header'} Course
            %hr/
            = image_tag @user.avatar.url(:thumb), :class => "payment-pic left"
            %h5 #{@user.first_name} #{@user.last_name}
            .row
              .term-details
                %h5 Terms:
                %h6{ style: 'margin-left: 10rem'}
                  - if @user.terms.present?
                    = @user.terms
                  - else
                    %span.default-content
                      Please update Terms in settings
            .row
              .course-details
                %h5 Course: 
                %h6 Category : #{@course.categories.name}
                %h6 Price: $#{@course.price} per fortnight
                = hidden_field_tag :course, @course.id
            .row
              .option-container
                %ul.center
                  %li
                    %input#option{:name => "options", :type => "radio", class: 'option-accept' }/
                    %label{:for => "option"} Accept
                  %li
                    %input#option2{:name => "options", :type => "radio", class: 'option-decline'}/
                    %label{:for => "option2"} Decline
          .payment-container      
            %h3{ class: 'header'} Payment
            %hr/
            %ul{ class: 'collection with-header'}
              = link_to new_payment_path , class: 'collection-item' do
                %i{ class: 'fa fa-plus-circle fa-2x'}
                  Add Credit Card
              - for payment in @payments
                %li.collection-item.avatar
                  = radio_button_tag :payment, payment.id, payment.id == current_user.default_payment_id,class: 'with-gap payment-course'
                  %label{ for: 'payment_' + payment.id.to_s, style: 'width: 100%' }
                    = image_tag payment_logo(payment.card_type), class: "circle", style: "left: 34px !important;"
                    %span.title{:style => "margin-left: 4rem;"}
                      = " Card: #{payment.masked_number}"
                    %p{:style => "margin-left: 4rem;"}
                      = " Type: #{payment.card_type}"
                    = link_to destroy_payment_path(payment), class: 'secondary-content', method: :delete, data: { confirm: 'Are you sure?' } do
                      %i.fa.fa-times.fa-2x.right

          .row.center
            = link_to user_path(@user) , class: 'prev-page waves-effect waves-light btn' do
              %i.fa.fa-angle-left
              Back
            %button{ type: 'submit', class: 'waves-effect waves-light btn', id: 'submit-course' } Next

app/views/users/show.html.haml
%ul#slide-out.side-nav.fixed
  %div{:style => "display: block;"}= image_tag @user.avatar.url(:thumb), :class => "circle mypic"
  %li
    %h4.center.navFont Welcome #{@user.first_name}!
  %li
    %h6.center.navFont How are you tracking so far...
  - courses = Course.where(user: @user)
  - if current_user.present?
    - @course_user_relation = current_user.courses_user_relations.where(owner: @user, course: courses).where('created_at >= ?', 2.week.ago)
    = hidden_field_tag :courses_user_relations, @course_user_relation.first.id if @course_user_relation.present?
  = render 'rating' if !@user.mentee?
  
  %h6.red-text.center.tooltipped#text-mentor-status{ data: {"delay": "100", "position": "bottom", "tooltip": "Sorry the mentor is booked out"}, class: "#{'hide' if @user.mentor_status}" }
    %i.fa.fa-lock{"aria-hidden" => "true"}
    Booked out
  
  - if @user == current_user and !@user.mentee?
    .input-field.col.s12
      %select.select-avail#select-availible
        %option{ value: 'true', selected: @user.mentor_status} Available
        %option.red-text{ value: 'false', selected: !@user.mentor_status} Booked Out
      %label Current Availability
  
  %hr/
  - if current_user.present?
    - if @user != current_user
      .col.s12
        - if @user.follows.where(follower: @user).first.present?
          %button.waves-effect.waves-light.btn.unfollow.profBtns{ id: 'js-follow-button' } Unfollow
        - else
          %button.waves-effect.waves-light.btn.follow.profBtns{ id: 'js-follow-button' } Follow

        - if current_user.transactions.where(course_owner: @user, status: 'holded').where('created_at >= ?', 1.week.ago).present?
          = link_to 'Contact', users_wait_path(@user) , class: 'waves-effect waves-light btn profBtns contact modal-contact-trigger' 
        - elsif @course_user_relation.where(user: current_user, owner: @user).where('created_at >= ?', 2.week.ago).present?
          = link_to 'Contact',  message_path(@user) , class: 'waves-effect waves-light btn profBtns contact modal-contact-trigger' 
        - elsif !@user.mentor_status
          %button.btn.disableBtns.contact Contact
        - else
          %button.waves-effect.waves-light.btn.profBtns.contact.modal-contact-trigger{"data-target" => "contact-modal"} Contact
          

  - if !@user.mentee?
    %li
      .areas{:style => "display: inline-block; width: 99%; text-align: center; background-color: #E6E7E8"}
        %span.left{:style => "font-size: 1.4rem; margin-top: 0.5rem; margin-left: 2rem; color: #36524E"}
          Areas:
        = image_tag 'images/icons/Finance.png', :class => "areas-icons" if @user.mentor_area_exist?(Category.where(name: 'Financial').first.id)
        = image_tag 'images/icons/Health.png', :class => "areas-icons" if @user.mentor_area_exist?(Category.where(name: 'Health and Fitness').first.id)
        = image_tag 'images/icons/Education.png', :class => "areas-icons" if @user.mentor_area_exist?(Category.where(name: 'Education').first.id)
        = image_tag 'images/icons/Relationships.png', :class => "areas-icons" if @user.mentor_area_exist?(Category.where(name: 'Relationships').first.id)
        = image_tag 'images/icons/Spirituality.png', :class => "areas-icons" if @user.mentor_area_exist?(Category.where(name: 'Spiritual').first.id)
        = image_tag 'images/icons/Work.png', :class => "areas-icons" if @user.mentor_area_exist?(Category.where(name: 'Career').first.id)
      
  = render 'terms' if !@user.mentee?

  <!-- End mentor and both section -->
    
  = render 'category' if !@user.mentor?

  <!-- Mentor and both section -->
  = render 'mentor' if @user.follows.mentors.present?

  = render 'mentee' if @user.follows.mentees.present?
    
  %p{ style: 'height: 65px;'}
  <!-- End mentor and both section -->

%a.button-collapse-other.left.hide-on-large-only{"data-activates" => "slide-out", :href => "#", :style => "font-size: 4rem; color: #36524E !important;"}
  %div{:style => "display: block;"}= image_tag @user.avatar.url(:thumb), :class => "circle mypicslide"

= render 'feed_message_container'

= render 'modal' if @user == current_user

= render 'modalContact' if @user != current_user

app/views/users/wait.html.erb
<div class="wait-container col s12 overlay-container">
    <div class="overlay"></div>
    <div class="center main-wait" style="">
        <!--<%= image_tag 'wait.jpg', :style => "width: 100%" %>-->
        <i class="fa fa-envelope animated infinite rollOut" style="font-size: -webkit-xxx-large; color: #01DFFF;" aria-hidden="true"></i>
        <h3>
            Request sent to the mentor!
        </h3>
        <h4>
           You will soon receive the response from the mentor. 
        </h4>
        <%= link_to user_path(@user) , class: 'waves-effect waves-purple btn-large back-button' do %>
          <i class="fa fa-angle-left" aria-hidden="true"></i> Back
        <% end %>
    </div>
</div>