config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions", :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_scope :user do
    get '/users/detail',  to: 'registrations#detail'
    put '/users/detail',  to: 'registrations#detail_update'
  end

  root 'home#index'
  get   '/terms',          to:  'home#terms'
  get   '/facebook_registration',          to:  'home#registration'
  put   '/facebook_registration',          to:  'home#registration_update'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :users

  get '/users/:id/payment', to: 'users#payment', as: :users_payment
  put '/users/:id/payment', to: 'users#transaction', as: :users_transaction
  get '/users/:id/wait', to: 'users#wait', as: :users_wait

  get '/dashboard',       to: 'dashboard#index'
  post '/rating',          to: 'users#rating'

  get '/settings',            to: 'settings#index'
  put '/settings',            to: 'settings#update'
  get '/settings/password',   to: 'settings#password', as: :settings_password
  put '/settings/password',   to: 'settings#change_password'
  get '/settings/payment',    to: 'settings#payment', as: :settings_payment
  put '/settings/payment',    to: 'payment#set_default'
  get '/settings/payment/new',to: 'settings#add_payment', as: :settings_add_payment
  get '/settings/category',   to: 'settings#category'
  get '/settings/mentor',   to: 'settings#mentor'
  put '/settings/mentor',   to: 'settings#mentor_create'
  put '/settings/mentor/detail',   to: 'settings#mentor_detail'
  put '/settings/mentor/update',   to: 'settings#mentor_update'
  put '/settings/mentor/status',   to: 'settings#mentor_status'


  get  '/payment',        to: 'payment#new', as: :new_payment
  post '/payment/:id/set_default', to: 'payment#set_default', as: :set_default_payment
  post '/payment',        to: 'payment#create'
  delete '/payment/:id',  to: 'payment#destroy', as: :destroy_payment


  put '/category/create_relation', to: 'category#create_category_user_relation'
  put '/category/delete_relation', to: 'category#delete_category_user_relation'
  put '/category/update_current', to: 'category#update_current'
  put '/category/update_desire', to: 'category#update_desire'
  put '/category/update_desire', to: 'category#update_desire'
  put '/category/relation', to: 'category#relation'
  put '/category/relation_one', to: 'category#relation_one'

  put '/feed_message',    to: 'feed_message#create'
  put '/feed_message/update',    to: 'feed_message#update'
  put '/feed_message/upload',    to: 'feed_message#upload'
  put '/feed_message/share',    to: 'feed_message#share'

  put '/follow',    to: 'follow#create'
  put '/follow/delete',    to: 'follow#delete'

  get '/notifications', to: 'notifications#index'
  post '/notifications/resources', to: 'notifications#resources'
  put '/notifications/delete', to: 'notifications#delete'

  put '/payment/accept', to: 'payment#accept'
  put '/payment/decline', to: 'payment#decline'

  resources :message

  put '/message/update', to: 'message#update'
  put '/reply/upload', to: 'conversation_reply#upload'
  post '/reply/delete', to: 'conversation_reply#delete'
  
  get  '/search',        to: 'search#new', as: :search

  get  '/resources',        to: 'resources#new', as: :resources
  put  '/resources/upload',        to: 'resources#upload'
  get  '/resources/admin',        to: 'resources#admin'
  put  '/resources/admin',        to: 'resources#upload_default'

end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :authenticate_user!
  before_action :incomplete_info_user!, except: [:index, :update]
  before_action :set_categories, only: [:mentor]

  def index

  end

  def update
    if current_user.update(user_params)
      flash.now[:notice] = "Update Personal Data Success"
    else
      flash.now[:notice] = current_user.errors.full_messages.first
    end
    render 'index'
  end

  def password
  end

  def change_password
    if current_user.valid_password?(params['user']['old_password'])
      if current_user.update(params.require(:user).permit(:password, :password_confirmation))
        flash[:notice] = "Change Password Success, Please Login Again"
        redirect_to new_user_session_path
      else
        flash.now[:notice] = current_user.errors.full_messages.first
        render 'password'
      end
    else
      flash.now[:notice] = "Your password is wrong."
      render 'password'
    end
  end

  def payment
    @payments = current_user.payments
  end

  def add_payment
    @client_token = generate_client_token
  end

  def category
    @category = Category.where(parent_id: nil)
  end

  def mentor
    if Course.where(user: current_user).first.present?
      set_course
    else
      @course = Course.new
    end
  end

  def mentor_status
    current_user.mentor_status = params[:mentor_status]
    current_user.save!
    render json: { success: true, status: 200 }
  end

  def mentor_detail
    category_arr = Array.new
    params[:user][:category].each do |val|
      current_user.courses.where(categories_id: val[:id]).first_or_initialize.tap do |course|
        course.price = val[:price]
        course.save
      end
      category_arr << val[:id].to_i
    end

    for course in current_user.courses
      unless category_arr.include?(course.categories_id)
        Course.where(user: current_user, categories_id: course.categories_id).destroy_all
      end
    end
    respond_to do |format|
      if current_user.update(mentor_detail_params)
        format.html { redirect_to settings_mentor_url, notice: 'Update Mentor Detail Success' }
        format.json { render :show, status: :ok, location: settings_mentor_url }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def mentor_create
    @course = Course.new(coures_params)

    @course.user = current_user

    respond_to do |format|
      if @course.save
        format.html { redirect_to settings_mentor_url, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: settings_mentor_url }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  def mentor_update 
    set_course
    respond_to do |format|
      if @course.update(coures_params)
        format.html { redirect_to settings_mentor_url, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: settings_mentor_url }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

private
  def set_course
    @course = Course.where(user: current_user).first
  end

  def set_categories
    @categories = Category.where(parent_id: nil)
  end
  def user_params
    hash_params = params.require(:user).permit(:first_name, :middle_name, :last_name, :gender, :education, :birthdate, :avatar, :address, :city, :state, :zipcode, :mobile_phone, :country, :prefered_language, :user_type)
    hash_params[:birthdate] = Date.strptime(hash_params[:birthdate],"%m/%d/%Y") unless hash_params[:birthdate].nil? 
    return hash_params
  end

  def coures_params
    params.require(:course).permit(:price)
  end

  def mentor_detail_params
    params.require(:user).permit(:about, :program, :terms)
  end
end

app/views/settings/_menu.html.haml
.collection.navigation-leftbar
  = link_to_unless_current 'Personal Data <i class="right fa fa-pencil" aria-hidden="true"></i>'.html_safe, settings_path, class: 'collection-item' do
    = link_to settings_path, class: 'collection-item active' do
      Personal Data 
      %i{ class: "right fa fa-pencil" }
  = link_to_unless_current 'Change password <i class="right fa fa-key fa-rotate-90" aria-hidden="true"></i>'.html_safe, settings_password_path, class: 'collection-item' do  
    = link_to settings_password_path, class: 'collection-item active' do
      Change password 
      %i{ class: "right fa fa-key fa-rotate-90" }
  = link_to_unless_current 'Default Payment<i class="right fa fa-credit-card-alt" aria-hidden="true"></i>'.html_safe, settings_payment_path, class: 'collection-item' do
    = link_to settings_payment_path, class: 'collection-item active' do
      Default Payment
      %i{ class: "right fa fa-credit-card-alt" }
      
  - if !current_user.mentor?
    = link_to_unless_current 'Category<i class="right fa fa-bar-chart" aria-hidden="true"></i>'.html_safe,  settings_category_path, class: 'collection-item' do
      = link_to  settings_category_path, class: 'collection-item active' do
        Category
        %i{ class: "right fa fa-bar-chart" }

  - if !current_user.mentee?
    = link_to_unless_current 'Mentor Setting<i class="right fa fa-newspaper-o" aria-hidden="true"></i>'.html_safe,  settings_mentor_path, class: 'collection-item' do
      = link_to  settings_mentor_path, class: 'collection-item active' do
        Mentor Setting
        %i{ class: "right fa fa-newspaper-o" }

app/views/settings/add_payment.html.haml
.row.setting-page
  .col.s3.left-content
    = render 'menu'
  .col.s9.right-content
    .row
      .form-fill
        %form{ id: 'js-payment-form', class: 'payment-form' }
          = render 'payment/payment_form'
          
      .row.center
        = link_to settings_payment_path , class: 'prev-page waves-effect waves-light btn' do
          %i.fa.fa-angle-left
          Back
        %a{ class: 'waves-effect waves-light btn', id: 'js-payment-submit' } Submit

app/views/settings/category.html.haml
.row.setting-page
  .col.s3.left-content
    = render 'menu'
  .col.s9.right-content
    .row
      = render 'category/category_list'
      %a{ class: 'waves-effect waves-light btn', id: 'refresh-submit' } Update

app/views/settings/index.html.haml
.row.setting-page
  .col.s3.left-content
    = render 'menu'
  .col.s9.right-content
    .row
      .form-fill
        = image_tag current_user.avatar.url(:thumb), :class => "right circle", :style => "height: 200px; width: 200px;"
        %h3{ class: 'left header'}
          My Profile
        = form_for(current_user, url: settings_path, html: { method: :put , class: 'col s12' }) do |f|
          .row
            .input-field.col.s12
              = f.text_field :first_name, data: { validation: "required" }, autofocus: true
              = f.label :first_name

            .input-field.col.s12
              = f.text_field :middle_name
              = f.label :middle_name

            .input-field.col.s12
              = f.text_field :last_name, data: { validation: "required" }
              = f.label :last_name

            .input-field.col.s12{:style => "margin-bottom: 40px"}
              .col.s1
                = f.label "Gender", style: 'font-size: 1.2rem'
              .col.s11
                = f.radio_button :gender, :male,:checked=> true, id: 'male', class: 'with-gap'
                = label :gender, 'Male', :for=>'male'
                = f.radio_button :gender, :female, id: 'female', class: 'with-gap'
                = label :gender, 'Female', :for=>'female'

            .input-field.col.s12
              = f.label :birthdate
              = f.text_field :birthdate, class: 'datepicker', value: (f.object.birthdate.strftime('%m/%d/%Y') if f.object.birthdate), data: { validation: "date", "validation-format": "mm/dd/yyyy" }

            .input-field.col.s12
              = f.select :education, options_for_select(educations, f.object.education), {prompt: "Select Education"}, { class: 'select-setting' }
              = f.label :education

            .input-field.col.s12
              = f.text_field :address
              = f.label :address

            .input-field.col.s12
              = f.label :city
              = f.text_field :city

            .input-field.col.s12
              = f.label :state
              = f.text_field :state

            .input-field.col.s12
              %label{ for: 'postcode'} Postcode
              = f.text_field :zipcode,  data: { validation: "required" }

            .input-field.col.s12
              = f.select :country, options_for_select(countries, f.object.country), {prompt: "Select Country"}, { class: 'select-setting' }
              = f.label :country

            .input-field.col.s12
              = f.label :mobile_phone
              = f.text_field :mobile_phone, :type=>"tel", autocomplete: "off"

            .input-field.col.s12
              = f.select :prefered_language, options_for_select(languages, f.object.prefered_language), {prompt: "Select Prefered Language"}, { class: 'select-setting' }
              = f.label :prefered_language

            .input-field.col.s12{:style => "margin-bottom: 40px"}
              .col.s1
                = f.label "Role", style: 'font-size: 1.2rem'
              .col.s11
                = f.radio_button :user_type, :mentee,:checked=> true, id: 'mentee', class: 'with-gap'
                = label :user_type, 'Mentee', :for=>'mentee'
                = f.radio_button :user_type, :mentor, id: 'mentor', class: 'with-gap'
                = label :user_type, 'Mentor', :for=>'mentor'
                = f.radio_button :user_type, :both, id: 'both', class: 'with-gap'
                = label :user_type, 'Both', :for=>'both'

            .file-field.input-field.col.s12
              .btn
                %span Profile Image
                = f.file_field :avatar
              .file-path-wrapper
                %input{ type: 'text', class: 'file-path validate'}
                
              

          .row
            = f.submit "Update", { class: 'waves-effect waves-light btn' }
              

app/views/settings/mentor.html.haml
.row.setting-page
  .col.s3.left-content
    = render 'menu'
  .col.s9.right-content
    .row
      .form-fill
        %h3.left.header
          Mentor Settings
        = form_for(current_user, url: settings_mentor_detail_path , html: { method: :put }) do |f|
          .row
            .input-field.col.s12
              = f.text_area :about, length: 120, class: 'materialize-textarea', placeholder: 'Something that describes you well...'
              = f.label :about
            .input-field.col.s12
              = f.text_area :program, length: 120, class: 'materialize-textarea', placeholder: 'Something that describes your program well...'
              = f.label :program
            .input-field.col.s12
              = f.text_area :terms, length: 100, class: 'materialize-textarea', placeholder: 'List all your terms here, Eg: Available only from 10am - 3pm Weekdays...'
              = f.label :terms
            .input-field.col.s12
              %select.select-areas{:multiple => "multiple", id: 'mentor-category-area'}
                - for category in @categories
                  %option{:value => "#{category.id}", selected: current_user.mentor_area_exist?(category)} #{category.name}
               
              %label Choose your areas

          .row
            %h4.left.header
              Mentor Fields
            - for category in @categories
              .col.s12{ class: 'mentor-categories-group', ref: category.id }
                .div-check
                  .col.s5{ style: 'padding-bottom: 20px;'}
                    %h5 #{category.name}
                - @sub_category = Category.where(parent_id: category.id)
                - for sub_category in @sub_category
                  .col.s12{ style: 'padding-left: 20px; padding-bottom: 20px;'}
                    .div-check
                      .col.s5
                        = check_box_tag "category_#{sub_category.id}", sub_category.id, category.category_course(current_user, sub_category.id).present?, {class: 'mentor_category_checkbox', ref: sub_category.id , name: 'user[category][][id]', parent: "#{category.id}"}
                        %label{ for: "category_#{sub_category.id}" }
                          %span.category_label #{sub_category.name}
                      .col.s4.mentor_category_price_div{ ref: "#{sub_category.id}"}
                        %input{ type: 'number', id: "category_price_#{sub_category.id}",min: '0', name: 'user[category][][price]', ref: "#{sub_category.id}", class: 'mentor_category_price', data: { validation: "number", 'validation-error-msg': "Fill price"  }, value: "#{category.category_course(current_user, sub_category.id).first.price if category.category_course(current_user, sub_category.id).present?}" }
                        %span{ class: 'prefix aud right'} 
                          AUD/Fortnight
                        %label{ for: "category_price_#{sub_category.id}" }

          .row
            = f.submit "Update Mentor Detail", { class: 'waves-effect waves-light btn' }

app/views/settings/password.html.haml
.row.setting-page
  .col.s3.left-content
    = render 'menu'
  .col.s9.right-content
    .row
      .form-fill
        %h3{ class: 'header'}
          Change Password

        = form_for(current_user, url: settings_password_path, html: { method: :put }) do |f|
          .row
            .input-field.col.s12
              = f.label :old_password, 'Old password'
              = f.password_field :old_password

            .input-field.col.s12
              = f.label :password, 'New password'
              = f.password_field :password

            .input-field.col.s12
              = f.label :password_confirmation, 'Confirm new password'
              = f.password_field :password_confirmation

          .actions
            = f.submit "Change password", { class: 'waves-effect waves-light btn' }

app/views/settings/payment.html.haml
.row.setting-page
  .col.s3.left-content
    = render 'menu'
  .col.s9.right-content
    .row
      .form-fill
        %h3{ class: 'header'}
          Payment
        .row
          = form_for(current_user, url: settings_payment_path, html: { method: :put }) do |f|
            %ul{ class: 'collection with-header'}
              = link_to settings_add_payment_path , class: 'collection-item' do
                %i{ class: 'fa fa-plus-circle fa-2x'}
                  Add Credit Card
              - for payment in @payments
                %li.collection-item.avatar
                  = f.radio_button :default_payment_id, payment.id, class: 'with-gap'
                  %label{ for: 'user_default_payment_id_' + payment.id.to_s, style: 'width: 100%' }
                    = image_tag payment_logo(payment.card_type), class: "circle", style: "left: 34px !important;"
                    %span.title{:style => "margin-left: 4rem;"}
                      = " Card: #{payment.masked_number}"
                    %p{:style => "margin-left: 4rem;"}
                      = " Type: #{payment.card_type}"
                    = link_to destroy_payment_path(payment), class: 'secondary-content', method: :delete, data: { confirm: 'Are you sure?' } do
                      %i.fa.fa-times.fa-2x.right

            .row.center
              = f.submit "Update", { class: 'waves-effect waves-light btn' }
                    