config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations", sessions: "sessions", :omniauth_callbacks => "omniauth_callbacks" }
  
  devise_scope :user do
    get '/users/detail',  to: 'registrations#detail'
    put '/users/detail',  to: 'registrations#detail_update'
  end

  root 'home#index'
  get   '/terms',          to:  'home#terms'
  get   '/facebook_registration',          to:  'home#registration'
  put   '/facebook_registration',          to:  'home#registration_update'

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  resources :users

  get '/users/:id/payment', to: 'users#payment', as: :users_payment
  put '/users/:id/payment', to: 'users#transaction', as: :users_transaction
  get '/users/:id/wait', to: 'users#wait', as: :users_wait

  get '/dashboard',       to: 'dashboard#index'
  post '/rating',          to: 'users#rating'

  get '/settings',            to: 'settings#index'
  put '/settings',            to: 'settings#update'
  get '/settings/password',   to: 'settings#password', as: :settings_password
  put '/settings/password',   to: 'settings#change_password'
  get '/settings/payment',    to: 'settings#payment', as: :settings_payment
  put '/settings/payment',    to: 'payment#set_default'
  get '/settings/payment/new',to: 'settings#add_payment', as: :settings_add_payment
  get '/settings/category',   to: 'settings#category'
  get '/settings/mentor',   to: 'settings#mentor'
  put '/settings/mentor',   to: 'settings#mentor_create'
  put '/settings/mentor/detail',   to: 'settings#mentor_detail'
  put '/settings/mentor/update',   to: 'settings#mentor_update'
  put '/settings/mentor/status',   to: 'settings#mentor_status'


  get  '/payment',        to: 'payment#new', as: :new_payment
  post '/payment/:id/set_default', to: 'payment#set_default', as: :set_default_payment
  post '/payment',        to: 'payment#create'
  delete '/payment/:id',  to: 'payment#destroy', as: :destroy_payment


  put '/category/create_relation', to: 'category#create_category_user_relation'
  put '/category/delete_relation', to: 'category#delete_category_user_relation'
  put '/category/update_current', to: 'category#update_current'
  put '/category/update_desire', to: 'category#update_desire'
  put '/category/update_desire', to: 'category#update_desire'
  put '/category/relation', to: 'category#relation'
  put '/category/relation_one', to: 'category#relation_one'

  put '/feed_message',    to: 'feed_message#create'
  put '/feed_message/update',    to: 'feed_message#update'
  put '/feed_message/upload',    to: 'feed_message#upload'
  put '/feed_message/share',    to: 'feed_message#share'

  put '/follow',    to: 'follow#create'
  put '/follow/delete',    to: 'follow#delete'

  get '/notifications', to: 'notifications#index'
  post '/notifications/resources', to: 'notifications#resources'
  put '/notifications/delete', to: 'notifications#delete'

  put '/payment/accept', to: 'payment#accept'
  put '/payment/decline', to: 'payment#decline'

  resources :message

  put '/message/update', to: 'message#update'
  put '/reply/upload', to: 'conversation_reply#upload'
  post '/reply/delete', to: 'conversation_reply#delete'
  
  get  '/search',        to: 'search#new', as: :search

  get  '/resources',        to: 'resources#new', as: :resources
  put  '/resources/upload',        to: 'resources#upload'
  get  '/resources/admin',        to: 'resources#admin'
  put  '/resources/admin',        to: 'resources#upload_default'

end

app/views/common/_carousel.html.erb
    <!-- Carousel Start -->
<div class="slider" style="">
  <ul class="slides">
    <li>
      <%= image_tag("slider/main.jpg") %>
      <div class="caption left-align">
        <h1 class="white-text c-text" style="text-shadow: 2px 2px 4px #000000;">Welcome aboard!</h1>
        <h3 class="light white-text" style="text-shadow: 1px 1px 2px #000000;">Grow yourself, Grow the planet.</h3>
      </div>
    </li>
    <li>
      <%= image_tag("slider/1.jpg") %>
      <div class="caption center-align">
        <h3 class="black-text t-text">I am not what happened to me. I am what I choose to become.</h3>
        <h5 class="light grey-text">~ Carl Jung</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/2.jpg") %>
      <div class="caption left-align">
        <h3 class="s-text">Smooth seas do not make skillful sailors.</h3>
        <h5 class="light grey-text text-lighten-3">~ African proverb</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/4.jpg") %>
      <div class="caption right-align">
        <h3 class="black-text l-text">Life is not about waiting for the storm to pass. It’s about learning to dance in the rain.</h3>
        <h5 class="light white-text">~ Anon</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/3.jpg") %>
      <div class="caption right-align">
        <h3 class="l-text">In the depth of winter, I finally learned that within me there lay an invincible summer.</h3>
        <h5 class="light grey-text text-lighten-3">~ Albert Camus</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/5.jpg") %>
      <div class="caption left-align">
        <h3 class="s-text">A positive attitude may not solve all your problems, but it will annoy enough people to make it worth the effort.</h3>
        <h5 class="light grey-text text-lighten-3">~ Herm Albright</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/6.jpg") %>
      <div class="caption center-align">
        <h3 class="c-text">Most of the shadows of this life are caused by our standing in our own sunshine.</h3>
        <h5 class="light grey-text text-lighten-3">~ Ralph Waldo Emmerson</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/7.jpg") %>
      <div class="caption right-align">
        <h3 class="t-text">Don’t think you’re on the right road just because it’s a well-beaten path.</h3>
        <h5 class="light grey-text text-lighten-3">~ Unknown</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/9.jpg") %>
      <div class="caption right-align">
        <h3 class="t-text">The real voyage of discovery consists of not in seeking new landscapes but in having new eyes.</h3>
        <h5 class="light grey-text text-lighten-3">~ Marcel Proust</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/extra.jpg") %>
      <div class="caption left-align">
        <h3 class="t-text">Write it on your heart that every day is the best day in the year.</h3>
        <h5 class="light grey-text text-lighten-3">~ Ralph Waldo Emmerson</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/10.jpg") %>
      <div class="caption left-align">
        <h3 class="s-text">Nothing in life is to be feared, it is only to be understood. Now is the time to understand more, so that we may fearless.</h3>
        <h5 class="light grey-text text-lighten-3">~ Marie Curie</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/13.jpg") %>
      <div class="caption left-align">
        <h3 class="l-text">To succeed in life, you need three things: a wishbone, a backbone and a funny bone.</h3>
        <h5 class="light grey-text text-lighten-3">~ Reba McEntire</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/12.jpg") %>
      <div class="caption center-align">
        <h3 class="t-text">Use your imagination, not to scare yourself to death; but to inspire yourself to live.</h3>
        <h5 class="light text-lighten-3">~ Adele Brockman</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/14.jpg") %>
      <div class="caption left-align">
        <h3 class="t-text">If you are brave enough to say goodbye, life will reward you with a new hello.</h3>
        <h5 class="light grey-text text-lighten-3">~ Paulo Coelho</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/15.jpg") %>
      <div class="caption right-align">
        <h3 class="t-text">Don’t fear failure so much that you refuse to try new things. The saddest summary of a life contains three descriptions: could have, might have, and should have.</h3>
        <h5 class="light grey-text text-lighten-3">~ Louis E. Boone</h5>
      </div>
    </li>
    <li>
      <%= image_tag("slider/16.jpg") %>
      <div class="caption left-align">
        <h3 class="black-text s-text">Waste your money and you’re only out of money, but waste your time and you’ve lost a part of your life.</h3>
        <h5 class="light black-text text-lighten-3">~ Michael Leboeuf</h5>
      </div>
    </li>
  </ul>
</div>
<!--Carousel end-->
<!--style="color: #FFEF99; text-shadow: 2px 2px black;"-->

app/views/common/_header.html.haml
.navbar-fixed
  %nav.main-header
    .nav-wrapper
      = link_to dashboard_path do
        .brand-logo
          = image_tag 'icon.png', class: 'header-icon', alt: 'menti icon'
          = image_tag 'logo.png', class: 'header-logo', alt: 'menti icon'
      %a{ href: '#!', data: { activates: 'mobile-demo'}, class: 'right button-collapse' }
        %i{ class: 'header-fa fa fa-bars', 'aria-hidden': 'true'}
      %ul{ class: 'right hide-on-med-and-down header-links'}
        - if user_signed_in?
          %li.tooltipped{data: { position: 'bottom', delay: 50, tooltip: 'Home' } }
            = link_to dashboard_path do
              %i.fa.fa-home.header-fa
          %li.tooltipped{data: { position: 'bottom', delay: 50, tooltip: 'Dashboard' } }
            = link_to user_path(current_user) do
              %i{ class: 'fa fa-user header-fa', 'aria-hidden': 'true'}
          %li.tooltipped{data: { position: 'bottom', delay: 50, tooltip: 'Search' } }
            = link_to search_path do
              %i{ class: 'fa fa-search header-fa', 'aria-hidden': 'true'}
          %li.tooltipped{data: { position: 'bottom', delay: 50, tooltip: 'Notifications' } }
            = link_to notifications_path do
              - if Notification.where(user: current_user, seen: false).present?
                %i.fa.fa-bell.header-fa.icon-grey.badge
              - else
                %i.fa.fa-bell.header-fa.icon-grey
          %li.tooltipped{data: { position: 'bottom', delay: 50, tooltip: 'Message' } }
            = link_to message_index_path do
              - @conversations = Conversation.where('user_one_id = ? OR user_two_id = ?', current_user.id, current_user.id)
              - if ConversationReply.where(conversation: @conversations, seen: false).where.not(user: current_user).present?
                %i.fa.fa-comment.header-fa.badge
              - else
                %i.fa.fa-comment.header-fa
          %li.tooltipped{data: { position: 'bottom', delay: 50, tooltip: 'Resources' } }
            = link_to resources_path do
              %i{ class: 'fa fa-book header-fa', 'aria-hidden': 'true'}
          %li.tooltipped{data: { position: 'bottom', delay: 50, tooltip: 'Settings' } }
            = link_to settings_path do
              %i.fa.fa-cog.header-fa
          %li.tooltipped{data: { position: 'bottom', delay: 50, tooltip: 'Logout' } }
            = link_to destroy_user_session_path, :method => :delete do
              %i.fa.fa-sign-out.header-fa
        - else
          %li.tooltipped{data: { position: 'bottom', delay: 50, tooltip: 'Home' } }
            = link_to root_path do
              %i.fa.fa-home.header-fa
          %li.tooltipped{data: { position: 'bottom', delay: 50, tooltip: 'Search' } }
            %a
              %i{ class: 'fa fa-search header-fa', 'aria-hidden': 'true'}
  
      %ul{ class: 'side-nav', id: 'mobile-demo'}
        - if user_signed_in?
          %li
            = link_to 'Home', dashboard_path, class: 'white-text side-links'
          %li
            = link_to 'My Profile', user_path(current_user), class: 'white-text side-links'
          %li
            %a{ href: '#!', class: 'white-text side-links' }
              Search
          %li
            = link_to 'Notifications', notifications_path, class: 'white-text side-links'
          %li
            = link_to 'Message', message_index_path, class: 'white-text side-links'
          %li
            %a{ href: '#!', class: 'white-text side-links' }
              Resources
          %li
            = link_to 'Setting', settings_path, class: 'white-text side-links'
          %li
            = link_to 'Sign Out', destroy_user_session_path, :method => :delete, class: 'white-text side-links'
        - else
          %li
            = link_to 'Home', root_path, class: 'white-text side-links'
          %li
            %a{ href: '#!', class: 'white-text side-links' }
              Search